application: re-rss
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /harvester
  script: feeds.harvester.application
  login: admin
- url: /static
  static_dir: static
- url: /feed/\w+/?
  script: app.application
- url: /.*
  script: app.application
  login: required

libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: "rerss.settings"
